### ISSUE TITLE
Set access level to public for class SettingsViewController

### ISSUE THREAD

**Issue by sDunda** [infinum/ios-collar#2]
https://github.com/infinum/ios-analytics-collector/blob/76f01c583a8d068d8405ca0b48907b59188cfbe7/Sources/AnalyticsCollector/Classes/Settings/SettingsViewController.swift#L11

Currently, we can not access SettingsViewController. One use case where public accessibility would be beneficial is to check if the analytics collector view is already shown. The user can be on the settings view, and we don't want to stack an additional analytics view because one is already shown beneath the settings view.

**Comment by fgulan** [comment]
This one is solved - will be available with first release.
